"""The Bridge/Fractal thesis tables from the analysis dict of `analyse_perturbation_thesis.py`.

`res[set][label]` is `report.analyse` output; set "val200" carries the counterfactual relabelings
and action perturbations, set "inpainting258" object removal and its controls. Model labels are
the driver's reader-facing LaTeX names; perturbation and score names come
from say_no.perturbation.names. Each file is one `table` float: `%` lines with provenance and
protocol detail, a caption that says what is shown, and the tabular.

Numbers: AUROC and Spearman rho as value $\\pm$ half-width of the 95 % paired bootstrap interval;
member-subset and split-half results as mean (min--max).
Marking rule: say_no.perturbation.tables.ranks (shared with the IVA tables).
Each table names its comparison group in its `%` lines; cells a detector should keep at chance
(background / re-encoding controls) and non-comparative quantities are not marked.
"""
from __future__ import annotations

import json
from pathlib import Path

from say_no.perturbation.names import (KNN_K, MAIN_CLASSIFIERS, SCORE_NAMES, SCORE_SYMBOLS, SOLE_RELABELING_NAME,
                                       condition_name, model_name, title_case)
from say_no.perturbation.tables import booktabs, ranks, stack, write_table

LANG = ("lang_swap_train", "lang_swap_pkl", "lang_swap_near")
MAIN_LANG = ("lang_swap_train", "lang_swap_near")  # the test-pool relabeling is appendix-only
CONTROLS = ("inpaint", "composite_local_r16", "composite_global_r16", "jpeg_orig")
MARKED_CONTROLS = ("inpaint", "composite_local_r16")  # higher = better; the other two should stay at 0.5
DATASETS = {"bridge": "Bridge", "fractal": "Fractal"}
ENS_SCORES = ("spread", "neg_mean_q")
DIGITS = 2
SIZE = "\\small\n\\setlength{\\tabcolsep}{5pt}"
NARROW = "\\footnotesize\n\\setlength{\\tabcolsep}{3pt}"  # six value columns do not fit \textwidth at SIZE
GENERATOR = ("generated by src/scripts/analyse_perturbation_thesis.py (say_no.perturbation.thesis_tables) from "
             "analysis_thesis/perturbation_thesis.json; do not edit; invocation: docs/REPRODUCE.md")
P_AUROC = ("AUROC: perturbed input (positive) vs. the same trajectory's original (negative); interval: "
           "paired bootstrap over trajectories, 2000 resamples; +- = (hi - lo) / 2 of that interval")
P_BOTH = ("average of both frames: SayNo scores computed on each member's Q averaged over the initial and final "
          "frame (sigma_Q of the two-frame mean member Q, -Qbar its negative mean); other detectors: mean of "
          "their two frame scores")
RELABEL_DEF = "instruction of another trajectory drawn from the training instruction stream"
P_RELABEL = (f"random relabeling: {RELABEL_DEF}; "
             "test pool: drawn from the other test trajectories; nearest-instruction: most similar training "
             "instruction by MUSE cosine (<= 0.95) that substitutes >= 1 content word")
P_RELABEL_SOLE = f"{SOLE_RELABELING_NAME.lower()}: {RELABEL_DEF}"  # floats with no other relabeling variant
P_RHO = "rho = 10 %: share of training samples counterfactually relabeled (labelled infeasible, reward -1 per step)"
P_DETECTORS = ("encoder novelty: Mahalanobis (Ledoit-Wolf) / cosine 5-NN distance of each member's own "
               "image-language encoding to the same member's encodings of 200 training-split trajectories, fit per "
               "source dataset, min over datasets, mean over members; CLIP novelty: same distances on CLIP ViT-B/32 "
               "image embeddings; CLIP alignment: negative image-instruction cosine; classifiers: p(infeasible)")


# ------------------------------------------------------------------------------------------ cells

def shown(v: float) -> float:
    return round(v, DIGITS)


def _num(v: float, mark: str | None, signed: bool = False) -> str:
    v = 0.0 if shown(v) == 0 else v  # no "-0.00"
    s = f"{v:+.{DIGITS}f}" if signed else f"{v:.{DIGITS}f}"
    return {None: s, "bold": r"\mathbf{" + s + "}", "underline": r"\underline{" + s + "}"}[mark]


def pm(cell: dict | None, mark: str | None = None, signed: bool = False, key: str = "auroc") -> str:
    """Value +- half-width of its 95 % interval, math mode."""
    if cell is None:
        return "--"
    lo, hi = cell["ci95"]
    return f"${_num(cell[key], mark, signed)}" + r"{\scriptstyle\,\pm\," + f"{(hi - lo) / 2:.{DIGITS}f}" + "}$"


def span(d: dict | None, mark: str | None = None, mean="mean", lo="min", hi="max") -> str:
    """Mean with (min--max); the range is dropped when it is a single value."""
    if d is None:
        return "--"
    s = f"${_num(d[mean], mark)}"
    if shown(d[lo]) != shown(d[hi]):
        s += r"{\scriptstyle\,(" + f"{d[lo]:.{DIGITS}f}" + r"\text{--}" + f"{d[hi]:.{DIGITS}f})" + "}"
    return s + "$"


def value(cell: dict | None, key: str = "auroc") -> float | None:
    return None if cell is None else cell[key]


def legend(scope: str, pm: bool = True) -> str:
    """Closing caption sentence: the comparison group of the marks. What +- and the marks mean is
    stated once in the metrics paragraph of the thesis (Section 4.1), not per caption; `pm` is kept
    for the call sites."""
    return f"Marks compare values {scope}."


def colspec(n: int) -> str:
    """Label column + n centred columns, no outer padding."""
    return "@{}l" + "c" * n + "@{}"


def group_row(text: str, ncol: int, first: bool) -> str:
    return ("" if first else "\\addlinespace[3pt]\n") + r"\multicolumn{" + str(ncol) + r"}{@{}l}{\textit{" + text + r"}} \\"


def indent(s: str) -> str:
    return r"\hspace{0.7em}" + s


def auc(r: dict, cond: str, frame: str, rd: str, ds: str | None = None) -> dict | None:
    table = r["auroc"] if ds is None else r["auroc_by_dataset"][ds]
    return table.get(cond, {}).get(frame, {}).get(rd)


def counts(res: dict, s: str) -> str:
    r = next(iter(res[s].values()))
    by = ", ".join(f"{k} {DATASETS[d]}" for d, k in r["n_by_dataset"].items())
    return f"{r['n_trajectories']} trajectories ({by})"


def write(out: Path, tabular: str, caption: str, label: str, notes: list[str], generator: str = GENERATOR,
          size: str = SIZE) -> None:
    write_table(out, [tabular], caption, label, size=size, comment="\n".join([f"{out.name} -- {generator}"] + notes))


def marked_rows(cells: list[list[dict | None]], by: str, eligible=None, key: str = "auroc") -> list[list[str | None]]:
    """Marks for a grid of cells, ranked per column (`by='col'`) or per row (`by='row'`);
    `eligible(i, j)` excludes cells from ranking."""
    n, m = len(cells), len(cells[0])
    ok = eligible or (lambda i, j: True)
    vals = [[value(cells[i][j], key) if ok(i, j) else None for j in range(m)] for i in range(n)]
    marks = [[None] * m for _ in range(n)]
    if by == "row":
        for i in range(n):
            marks[i] = ranks(vals[i], digits=DIGITS)
    elif by == "col":
        for j in range(m):
            col = ranks([vals[i][j] for i in range(n)], digits=DIGITS)
            for i in range(n):
                marks[i][j] = col[i]
    else:
        raise ValueError(by)
    return marks


# ------------------------------------------------------------------------------ detector families

def classifier_group(sole_relabeling: bool) -> str:
    """Header of the classifier rows; names their training relabeling as condition_name does."""
    return f"Classifiers (trained with {condition_name('lang_swap_train', sole_relabeling).lower()})"


def detector_blocks(ens: list[str], cls: list[str], clip: dict[str, str], encoder: bool,
                    clip_scores: tuple[str, ...], sole_relabeling: bool,
                    encoder_scores: tuple[str, ...] = ("enc_mahalanobis", "enc_knn")) -> list[tuple[str, list[tuple[str, str, str]]]]:
    """[(group label, [(model label, score key, row name)])]: SayNo variants, their encoder novelty,
    classifiers, CLIP -- the one row order of every detector table. `sole_relabeling`: the table shows
    no relabeling variant next to the classifiers' training one (names it as condition_name does)."""
    blocks = [(model_name(lab), [(lab, rd, SCORE_NAMES[rd]) for rd in ENS_SCORES]) for lab in ens]
    if encoder and len(encoder_scores) == 1:
        rd = encoder_scores[0]
        blocks.append((f"Encoder novelty, {SCORE_NAMES[rd]}", [(f"{lab} | {rd}", rd, model_name(lab)) for lab in ens]))
    elif encoder:
        blocks += [(f"Encoder novelty, {model_name(lab)}", [(f"{lab} | {rd}", rd, SCORE_NAMES[rd]) for rd in encoder_scores])
                   for lab in ens]
    blocks.append((classifier_group(sole_relabeling), [(lab, "p_infeasible", model_name(lab)) for lab in cls]))
    blocks.append((clip["label"], [(clip[rd], rd, SCORE_NAMES[rd]) for rd in clip_scores]))
    return blocks


def detector_table(res_set: dict, blocks, columns, head_groups, marked, unranked: tuple[str, ...] = ()) -> str:
    """columns: [(header, fn(model result, score key) -> cell, kind)], kind 'auroc' (value +- CI
    half-width) or 'op' (split-half recall, mean (min--max)); marked(j): column j is ranked
    across all detector rows."""
    flat = [(lab, rd, name) for _, rows in blocks for lab, rd, name in rows]
    cells = [[fn(res_set[lab], rd) for _, fn, _ in columns] for lab, rd, _ in flat]
    key = {"auroc": "auroc", "op": "tpr_mean"}
    marks = [[None] * len(columns) for _ in flat]
    for j, (_, _, kind) in enumerate(columns):
        if marked(j):
            eligible = [rd not in unranked for _, rd, _ in flat]
            for i, m in enumerate(ranks([value(row[j], key[kind]) for row in cells], eligible=eligible, digits=DIGITS)):
                marks[i][j] = m
    fmt = {"auroc": lambda c, m: pm(c, m), "op": lambda c, m: span(c, m, "tpr_mean", "tpr_min", "tpr_max")}
    ncol = 1 + len(columns)
    body, i = [], 0
    for g, (group, rows) in enumerate(blocks):
        body.append(group_row(group, ncol, g == 0))
        for _, _, name in rows:
            body.append([indent(name)] + [fmt[kind](c, m) for (_, _, kind), c, m in zip(columns, cells[i], marks[i])])
            i += 1
    return booktabs(["Detector"] + [h for h, _, _ in columns], body, align=colspec(len(columns)),
                    group_header=head_groups)


# ----------------------------------------------------------------------------------------- tables

Z_NOTE = ("z~_p = (u_p - mu~_p) / s~_p with u_p = -Qbar_p per frame position p in {initial, final}; mu~_p, "
          "s~_p: mean / std of u_p over originals of the other fold (2-fold cross-fitting over trajectories); z~: "
          "mean of z~_p; |z~|: mean of |z~_p|; z~_final - z~_init: (z~_final - z~_initial) / 2")


def _score_rows(res, ens, rds, out: Path, caption: str, label: str, group: str) -> None:
    """Rows: detection scores `rds` per SayNo variant; columns: random and nearest-instruction relabeling,
    object removal; marks within one variant and column."""
    cols = [("val200", c) for c in MAIN_LANG] + [("inpainting258", "inpaint")]
    body = []
    for g, lab in enumerate(ens):
        cells = [[auc(res[s][lab], c, "both", rd) for s, c in cols] for rd in rds]
        marks = marked_rows(cells, "col")
        body.append(group_row(model_name(lab), 1 + len(cols), g == 0))
        body += [[indent(SCORE_NAMES[rd])] + [pm(c, m) for c, m in zip(cr, mr)] for rd, cr, mr in zip(rds, cells, marks)]
    t = booktabs(["Detection Score"] + [stack(*title_case(condition_name(c)).rsplit(" ", 1)) for _, c in cols], body,
                 align=colspec(len(cols)))
    write(out, t, caption + legend("per model and perturbation"), label,
          [P_AUROC, Z_NOTE, P_RELABEL, P_RHO, f"comparison group: {group} of one SayNo variant in one column"])


def time_normalised(res, ens, out: Path) -> None:
    _score_rows(res, ens, ("neg_mean_q", "neg_z", "spread"), out,
                "AUROC of the value score before and after time normalization, next to ensemble disagreement, on "
                "held-out Bridge and Fractal demonstrations pooled (set sizes in Appendix~\\ref{sec:app-protocols}). "
                "Time normalization standardizes the value score $-\\bar Q$ of each frame with the "
                "originals of other demonstrations at the same frame position. Two further versions are compared in "
                "Table~\\ref{tab:bf-time-normalised-variants}. ", "tab:bf-time-corrected", "the three scores")


def time_normalised_variants(res, ens, out: Path) -> None:
    _score_rows(res, ens, ("neg_z", "abs_z", "z_gap"), out,
                "AUROC of three time-normalized versions of the value score on the held-out Bridge and Fractal "
                "demonstrations of Table~\\ref{tab:bf-time-corrected}: the standardized value $\\tilde z$ averaged "
                "over the initial and final frame, its absolute value $|\\tilde z|$, and its change "
                "$\\tilde z_\\text{final} - \\tilde z_\\text{init}$ between the two frames, which needs both "
                "frames and is therefore not an online score. ", "tab:bf-time-normalised-variants",
                "the three time-normalized versions")


def member_count(res, ens, out: Path) -> None:
    ks = ("1", "2", "4", "8")
    cols = [("val200", "lang_swap_train", rd) for rd in ENS_SCORES] + [("inpainting258", "inpaint", rd) for rd in ENS_SCORES]
    body = []
    for g, lab in enumerate(ens):
        grid = [[res[s][lab]["member_subsets"][c].get(k, {}).get(rd) for s, c, rd in cols] for k in ks]
        marks = marked_rows(grid, "col", key="mean")
        body.append(group_row(model_name(lab), 1 + len(cols), g == 0))
        body += [[indent(k)] + [span(d, m) for d, m in zip(row, mr)] for k, row, mr in zip(ks, grid, marks)]
    t = booktabs(["Members $K$"] + [SCORE_SYMBOLS[rd] for *_, rd in cols], body, align=colspec(len(cols)),
                 group_header=[("", 1), (title_case(condition_name("lang_swap_train", sole_relabeling=True)), 2),
                               (title_case(condition_name("inpaint")), 2)])
    write(out, t, "AUROC of ensemble disagreement and value score for ensembles of $K$ members drawn from the "
          "eight-member SayNo critic ensembles. Each cell gives the mean and, in parentheses, the range over 50 "
          "random member subsets; $K = 8$ is the full ensemble, and disagreement is undefined for one member. "
          f"{counts(res, 'val200')} of the test split for "
          f"relabeling, {counts(res, 'inpainting258')} for object removal. " + legend("per model and column", pm=False),
          "tab:bf-member-count",
          [P_AUROC.split(";")[0], "subsets: 50 draws without replacement per K < 8, seed 0; K = 1: -Q of one member",
           P_BOTH, P_RELABEL_SOLE, P_RHO, "comparison group: the four ensemble sizes of one SayNo variant in one column "
           "(ranked by the mean over subsets)"])


def action_perturbations(res, ens, actions: list[str], out: Path) -> None:
    cells = [[auc(res["val200"][lab], a, "both", rd) for lab in ens for rd in ENS_SCORES] for a in actions]
    marks = marked_rows(cells, "row")
    body = [[condition_name(a)] + [pm(c, m) for c, m in zip(cr, mr)] for a, cr, mr in zip(actions, cells, marks)]
    t = booktabs(["Action Perturbation"] + [SCORE_SYMBOLS[rd] for _ in ens for rd in ENS_SCORES], body,
                 align=colspec(2 * len(ens)), group_header=[("", 1)] + [(model_name(lab), 2) for lab in ens])
    write(out, t, "AUROC of ensemble disagreement $\\sigma_Q$ and value score $-\\bar Q$ when the action is replaced "
          "and image and instruction stay unchanged. "
          f"{counts(res, 'val200')} of the test split. "
          + legend("per action perturbation"), "tab:bf-action-perturbation",
          [P_AUROC, P_BOTH, P_RHO,
           "far action: in-bounds action farthest (nearest-neighbour distance, 6 arm dims) from the source dataset's "
           "demonstrated actions; other trajectory's action: action of another trajectory at the same frame; "
           "negated / scaled x3: arm dims; flipped gripper: gripper command inverted; uniform random: arm dims "
           "uniform in [-1, 1], random gripper",
           "comparison group: the four scores in one row"])


def relabeling_frames(res, ens, out: Path) -> None:
    frames = ("first", "last", "both")
    body, g = [], 0
    ncol = 1 + len(ENS_SCORES) * len(frames)
    for lab in ens:
        r = res["val200"][lab]
        for c in LANG:
            name = condition_name(c)
            body.append(group_row(f"{model_name(lab)}: {name[0].lower()}{name[1:]}", ncol, g == 0))
            g += 1
            for d in (None, *DATASETS):
                row = [indent("All" if d is None else DATASETS[d])]
                for rd in ENS_SCORES:
                    cells = [auc(r, c, f, rd, d) for f in frames]
                    row += [pm(x, m) for x, m in zip(cells, ranks([value(x) for x in cells], digits=DIGITS))]
                body.append(row)
    t = booktabs(["Source Data"] + ["Initial", "Final", "Average"] * len(ENS_SCORES), body,
                 align=colspec(ncol - 1),
                 group_header=[("", 1)] + [(title_case(SCORE_NAMES[rd]), len(frames)) for rd in ENS_SCORES])
    write(out, t, "AUROC of ensemble disagreement and value score under counterfactual relabeling, per frame and "
          "per source dataset. Initial and final use one frame; average scores the member values $q_{k,t}$ averaged "
          "over both frames. "
          f"{counts(res, 'val200')} of the test split. " + legend("among the three frame choices of one score"),
          "tab:bf-langswap-frame", [P_AUROC, P_BOTH, P_RELABEL, P_RHO,
                                    "comparison group: initial / final / average of one score in one row"])


def random_vs_nearest(res, ens, cls, clip, out: Path) -> None:
    blocks = detector_blocks(ens, cls, clip, encoder=False, clip_scores=("clip_alignment",), sole_relabeling=False)
    heads = {"lang_swap_train": stack("Random", "Relabeling"), "lang_swap_near": stack("Nearest-", "Instruction")}
    cols = ([(heads[c], lambda r, rd, c=c: auc(r, c, "both", rd), "auroc") for c in MAIN_LANG] +
            [(n, lambda r, rd, d=d: auc(r, "lang_swap_near", "both", rd, d), "auroc") for d, n in DATASETS.items()])
    t = detector_table(res["val200"], blocks, cols,
                       [("", 1), ("All Trajectories", len(MAIN_LANG)), ("Nearest-Instruction", 2)],
                       marked=lambda j: True)
    write(out, t, "AUROC of every detector under random and nearest-instruction relabeling. The last two columns "
          "split nearest-instruction relabeling by source dataset; the classifiers were trained with random "
          f"relabeling. {counts(res, 'val200')} of the test "
          "split. " + legend("per column"), "tab:bf-near-swap",
          [P_AUROC, P_BOTH, P_RELABEL, P_RHO, P_DETECTORS, "comparison group: all detector rows in one column",
           "random relabeling (test pool) left out for width: SayNo in bf_relabeling_frame_auroc, classifiers per "
           "source dataset in bf_classifier_variants_auroc, all detectors in perturbation_thesis.json"])


def detector_comparison(res, ens, cls, clip, out: Path) -> None:
    blocks = detector_blocks(ens, cls, clip, encoder=True, clip_scores=("clip_alignment", "clip_knn"),
                             encoder_scores=("enc_knn",), sole_relabeling=False)
    image_only = ("clip_knn",)  # scores the image alone: undefined under a changed instruction
    cols = [(stack(*title_case(condition_name(c)).rsplit(" ", 1)),
             lambda r, rd, c=c, s=s: None if (c != "inpaint" and rd in image_only) else auc(res[s][r], c, "both", rd),
             "auroc") for s, c in (("val200", "lang_swap_train"), ("val200", "lang_swap_near"), ("inpainting258", "inpaint"))]
    # detector_table looks rows up in one result set; cells here pick their set per column, so pass labels through
    t = detector_table({lab: lab for _, rows in blocks for lab, _, _ in rows}, blocks, cols, None,
                       marked=lambda j: True, unranked=image_only)
    write(out, t, "AUROC of SayNo and the baselines under the three perturbations. CLIP novelty scores the image "
          "alone, so it is undefined under relabeling and, under object removal, responds to the re-rendered image "
          "rather than the removed object (Appendix~\\ref{sec:app-object-removal-controls}); it is not ranked. " + legend("per column"),
          "tab:bf-detector-comparison",
          [P_AUROC, P_BOTH, P_RELABEL, P_RHO, P_DETECTORS, f"novelty: k = {KNN_K}; Mahalanobis rows, ResNet--MUSE runs "
           "1-2 and per-dataset values in the appendix tables", "comparison group: all ranked detector rows in one column"])


P_OPERATING_POINT = ("threshold: split conformal (1 - alpha) quantile, alpha = {alpha}, of the average-of-both-frames "
                     "score on the originals of a random half of the pairs; recall = TPR on the perturbed inputs of the "
                     "other half; 200 random halves, seed 0; the realised false-alarm rate (mean over halves) rounds to "
                     "alpha for every row (asserted by the generator)")


def object_removal_recall(res, blocks, alpha: str):
    """Cell fn (model result, score key) -> split-half operating point of object removal at `alpha`;
    first asserts every row's realised false-alarm rate rounds to alpha."""
    op = lambda r, rd: r["operating_point"]["readouts"][rd]["split_half_test_originals"][alpha]
    for _, rows in blocks:
        for lab, rd, _ in rows:
            fpr = op(res["inpainting258"][lab], rd)["fpr_mean"]
            if shown(fpr) != shown(float(alpha)):
                raise ValueError(f"{lab}/{rd}: realised false-alarm rate {fpr:.3f} does not round to alpha {alpha}")
    return op


def object_removal_operating_point(res, ens, cls, clip, alpha: str, out: Path) -> None:
    blocks = detector_blocks(ens, cls, clip, encoder=True, clip_scores=("clip_mahalanobis", "clip_knn", "clip_alignment"),
                             sole_relabeling=True)
    a = float(alpha)
    frame_cols = [(t, lambda r, rd, f=f: auc(r, "inpaint", f, rd), "auroc") for f, t in
                  (("first", "Initial"), ("last", "Final"), ("both", "Average"))]
    op = object_removal_recall(res, blocks, alpha)
    t = detector_table(res["inpainting258"], blocks, frame_cols + [("Recall", op, "op")],
                       [("", 1), ("AUROC", 3), (stack(rf"{100 * a:.0f}\,\% of Originals", "Flagged"), 1)],
                       marked=lambda j: True)
    write(out, t, "AUROC of every detector under object removal, and the share of perturbed inputs flagged at a "
          f"threshold that flags {100 * a:.0f}\\,\\% of the originals (trajectory-level false-alarm rate). "
          f"{counts(res, 'inpainting258')}, each pair checked by eye. Recall: mean and, in "
          "parentheses, range over 200 random halves, the threshold being calibrated on the originals of one half "
          "and applied to the other. " + legend("per column", pm=False), "tab:bf-inpainting-operating-point",
          [P_AUROC, P_BOTH, P_RHO, P_DETECTORS, P_OPERATING_POINT.format(alpha=alpha),
           "comparison group: all detector rows in one column"])


def controls(res, ens, cls, clip, masks: dict, alpha: str, out: Path) -> None:
    blocks = detector_blocks(ens, cls, clip, encoder=True, clip_scores=("clip_mahalanobis", "clip_knn", "clip_alignment"),
                             sole_relabeling=True)
    pct = round(100 * float(alpha))
    cols = [(stack(*title_case(condition_name(c)).rsplit(" ", 1)), lambda r, rd, c=c: auc(r, c, "both", rd), "auroc")
            for c in CONTROLS] + [(stack(rf"Recall at {pct}\,\%", "of Originals", "Flagged"),
                                   object_removal_recall(res, blocks, alpha), "op")]
    t = detector_table(res["inpainting258"], blocks, cols, None,
                       marked=lambda j: j == len(CONTROLS) or CONTROLS[j] in MARKED_CONTROLS)
    write(out, t, "AUROC of every detector under object removal and three controls that separate the removed object "
          "from image artifacts (definitions in Appendix~\\ref{sec:app-object-removal-controls}), and the recall "
          f"under object removal at a threshold that flags {pct}\\,\\% of the originals. "
          f"{counts(res, 'inpainting258')}. Recall: mean and, in parentheses, range over 200 random halves of "
          "the trajectories. "
          + legend("per column for object removal, the edit-region control and the recall, where a detector of the "
                   "object should score high", pm=False),
          "tab:bf-inpainting-controls",
          [P_AUROC, P_BOTH, P_RHO, P_DETECTORS, P_OPERATING_POINT.format(alpha=alpha),
           f"edit region: pixels with max-channel |inpainted - original| > {masks['mask_threshold']}, dilated 16 px "
           f"(median {100 * masks['area_median']:.1f} % of the frame); edit-region control: inpainted inside the region, "
           "original outside; background control: original inside, inpainted outside; re-encoding control: original "
           f"JPEG-encoded at quality {masks['jpeg_quality']}, chosen to match the median per-pixel change of object "
           f"removal ({masks['median_delta']:.0f} grey levels)",
           "comparison group: all detector rows in the object-removal, edit-region and recall columns; background "
           "and re-encoding columns not marked (a detector of the object should stay at 0.5 there)"],
          size=NARROW)


def encoder_novelty(res, ens, spearman: dict, out: Path) -> None:
    conds = ([("inpainting258", c) for c in CONTROLS] + [("val200", c) for c in MAIN_LANG])
    marked_conds = set(MARKED_CONTROLS) | set(MAIN_LANG)
    body = []
    for g, (s, c) in enumerate(conds):
        body.append(group_row(condition_name(c), 6, g == 0))
        for lab in ens:
            rs = res[s]
            cells = [auc(rs[lab], c, "both", "spread"), auc(rs[f"{lab} | enc_mahalanobis"], c, "both", "enc_mahalanobis"),
                     auc(rs[f"{lab} | enc_knn"], c, "both", "enc_knn")]
            marks = ranks([value(x) for x in cells], digits=DIGITS) if c in marked_conds else [None] * 3
            rho = [spearman[s][lab][c][m] for m in ("enc_mahalanobis", "enc_knn")]
            body.append([indent(model_name(lab))] + [pm(x, m) for x, m in zip(cells, marks)] +
                        [pm(x, None, signed=True, key="rho") for x in rho])
    knn = "$k$-NN"  # k = KNN_K is stated once in the thesis appendix, not in every label
    t = booktabs(["SayNo Variant", "$\\sigma_Q$", "Mahalanobis", knn, "Mahalanobis", knn], body,
                 align=colspec(5), group_header=[("", 1), ("AUROC", 3),
                                              (stack("Spearman Correlation", "with Change in $\\sigma_Q$"), 2)])
    write(out, t, "Ensemble disagreement $\\sigma_Q$ compared with novelty measured in SayNo's own encoder features "
          f"(Mahalanobis and {knn} distance). The AUROC columns score each perturbation; the last two columns give "
          "the Spearman correlation, across trajectories, between the change of a novelty score and the change of "
          "$\\sigma_Q$ from the original to the perturbed input. "
          f"Object removal and controls on {counts(res, 'inpainting258')}, relabeling on "
          f"{counts(res, 'val200')} of the test split. "
          + legend("among the three AUROC columns of a row, except for the background and re-encoding controls"),
          "tab:bf-encoder-novelty",
          [P_AUROC, P_BOTH, P_RELABEL, P_RHO, P_DETECTORS,
           "Spearman rho across trajectories between paired shifts (perturbed - original) of the novelty score and of "
           "sigma_Q, both at the average of both frames; +- from a bootstrap over trajectories (2000 resamples)",
           "comparison group: sigma_Q vs the two encoder-novelty AUROCs in one row; rho columns and the background / "
           "re-encoding rows not marked"],
          size=NARROW)


def classifier_parts(lab: str) -> tuple[str, str]:
    """'ResNet--MUSE 1 (per trajectory)' -> ('ResNet--MUSE 1', 'per trajectory') for stacked headers."""
    name, sep, unit = lab.partition(" (")
    if not sep or not unit.endswith(")"):
        raise ValueError(f"classifier label must read 'NAME (RELABELING UNIT)', got {lab!r}")
    return name, unit[:-1]


# row names where the column header already says "Perturbation" and width is tight
SHORT = {"lang_swap_train": "Random relabeling", "lang_swap_pkl": "Random, test pool",
         "lang_swap_near": "Nearest-instruction", "inpaint": "Object removal"}


def classifier_variants(res, cls, notes: dict, out: Path) -> None:
    conds = list(LANG) + ["inpaint"]
    body, g = [], 0
    for d, dn in DATASETS.items():
        body.append(group_row(f"{dn} trajectories", 1 + len(cls), g == 0))
        g += 1
        for c in conds:
            s = "inpainting258" if c == "inpaint" else "val200"
            cells = [auc(res[s][lab], c, "both", "p_infeasible", d) for lab in cls]
            body.append([indent(SHORT[c])] + [pm(x, m) for x, m in zip(cells, ranks([value(x) for x in cells], digits=DIGITS))])
    head = [stack(name, r"{\footnotesize " + unit + "}", r"{\footnotesize\textit{" + notes[lab] + "}}")
            for lab in cls for name, unit in [classifier_parts(lab)]]
    t = booktabs(["Perturbation"] + head, body, align=colspec(len(cls)))
    write(out, t, "AUROC of the feasibility classifiers per source dataset. All classifiers output $p(\\text{infeasible})$ "
          "and were trained with 50\\,\\% randomly relabeled samples for 100k steps; they differ in backbone, "
          "training data and whether the relabeling is drawn once per trajectory or per sample. "
          + legend("per row"), "tab:classifier-ablations",
          [P_AUROC, P_BOTH, P_RELABEL,
           "ResNet--MUSE: ResNet-34 + FiLM image encoder, MUSE language encoder, same family as SayNo; Octo: "
           "pretrained Octo-small, full finetune; per trajectory: one relabeled instruction for a whole training "
           "trajectory; per sample: fresh relabeling per training sample; relabeling implementation of the "
           "ResNet--MUSE runs inferred from run dates, not pinned by the checkpoints",
           f"relabeling: {counts(res, 'val200')}; object removal: {counts(res, 'inpainting258')}",
           "comparison group: the four classifiers in one row"])


def reward_ablation(res, labels, reference: str, out: Path) -> None:
    cols = [("val200", c) for c in LANG] + [("val200", "act_far"), ("inpainting258", "inpaint")]
    body, ncol = [], 1 + len(cols)
    k_abl = {res["val200"][lab]["n_members"] for lab in labels}
    if len(k_abl) != 1:
        raise ValueError(f"ablation ensembles differ in size: {k_abl}")
    k_ref = res["val200"][reference]["n_members"]
    for g, rd in enumerate(ENS_SCORES):
        cells = [[auc(res[s][lab], c, "both", rd) for s, c in cols] for lab in labels + [reference]]
        marks = marked_rows(cells, "col", lambda i, j: i < len(labels))
        body.append(group_row(SCORE_NAMES[rd], ncol, g == 0))
        names = [model_name(lab) for lab in labels] + [f"Reference, $K = {k_ref}$"]
        body += [[indent(n)] + [pm(c, m) for c, m in zip(cr, mr)] for n, cr, mr in zip(names, cells, marks)]
    head = [stack("Random", "Relabeling"), stack("Random", "(Test Pool)"), stack("Nearest-", "Instruction"),
            stack("Far", "Action"), stack("Object", "Removal")]
    t = booktabs(["Training"] + head, body, align=colspec(len(cols)))
    k = next(iter(k_abl))
    write(out, t, f"AUROC of SayNo variants with $K = {k}$ members trained on Bridge only, with and without a terminal "
          "penalty on relabeled training samples. The reference row of each block is the "
          f"{k_ref}-member {model_name(reference)} trained on Bridge and Fractal, for scale. "
          f"Relabeling and far action on {counts(res, 'val200')} of the test split, object removal on "
          f"{counts(res, 'inpainting258')}. " + legend(f"per column among the $K = {k}$ variants"),
          "tab:bf-reward-ablation-per-sample",
          [P_AUROC, P_BOTH, P_RELABEL,
           f"ablations: {k}-member ensembles, 200k steps, Bridge only; penalty: terminal reward of relabeled training "
           "trajectories (rho = 5 %), printed as SayNo-CR, penalty ...; SayNo: same recipe without relabeled samples",
           "comparison group: the five Bridge-only variants in one column and score block; reference row not marked"])


def latency(path: Path, out: Path) -> dict:
    lat = json.loads(path.read_text(encoding="utf-8"))
    body = [group_row("SayNo critic ensemble, GPU", 5, True)]
    body += [[indent(str(c["members"])), str(c["rows"]), f"{c['median_ms']:.1f}", f"{c['p90_ms']:.1f}",
              f"{c['hz_at_median']:.0f}"] for c in lat["critic"]]
    mu = lat["muse_encode_one_instruction_cpu"]
    body += [group_row("MUSE language encoder, CPU, one instruction", 5, False),
             [indent("--"), "--", f"{mu['median_ms']:.1f}", f"{mu['p90_ms']:.1f}", f"{mu['hz_at_median']:.0f}"]]
    t = booktabs(["Members $K$", stack("Actions", "per Call"), stack("Median", "(ms)"), stack("90th Percentile", "(ms)"),
                  stack("Rate at", "Median (Hz)")], body, align=colspec(4))
    dev = lat["device"].replace("NVIDIA ", "NVIDIA~")
    write(out, t, f"Inference latency of the SayNo critic ensemble on one {dev} GPU for one observation and a number "
          "of candidate actions (more than one, e.g., when the candidates of a sampling policy are scored). The "
          "instruction embedding is computed once per instruction on the CPU and is not included in the critic rows. "
          "Median over timed calls; the rate is 1000 divided by the unrounded median.", "tab:bf-latency",
          [f"JAX {lat['jax']}, jit-compiled, one 256x256 image, {lat['n_calls']} timed calls after {lat['warmup']} "
           "warm-up; the image encoder is re-run for every action row (no shared encoding); rate = 1000 / median ms",
           "no marks: rows are configurations, not alternatives"])
    return lat


def clip_labels(clip_label: str) -> dict[str, str]:
    return {rd: f"{clip_label} | {rd}" for rd in ("clip_mahalanobis", "clip_knn", "clip_alignment")}


def encoder_labels(ens: list[str]) -> list[str]:
    return [f"{lab} | {rd}" for lab in ens for rd in ("enc_mahalanobis", "enc_knn")]


# thesis file names
FILES = {"time_normalised": "bf_time_normalised_value_score.tex",
         "time_normalised_variants": "bf_time_normalised_variants_auroc.tex", "member_count": "bf_ensemble_size_auroc.tex",
         "actions": "bf_action_perturbation_auroc.tex", "frames": "bf_relabeling_frame_auroc.tex",
         "nearest": "bf_random_vs_nearest_relabeling_auroc.tex", "all": "bf_detector_comparison_auroc.tex",
         "operating_point": "bf_object_removal_operating_point.tex", "controls": "bf_object_removal_controls.tex", "encoder": "bf_encoder_novelty_vs_disagreement.tex",
         "classifiers": "bf_classifier_variants_auroc.tex", "reward": "bf_reward_penalty_ablation_auroc.tex",
         "latency": "bf_latency.tex"}


def write_all(res: dict, spearman: dict, masks: dict, roles: dict, latency_json: Path, out: Path) -> dict:
    """Every thesis table into `out`. roles: main_ensembles, classifiers, classifier_notes, ablations,
    reference_ensemble, clip_label, table_alpha, actions. Returns the latency record."""
    ens, cls_all = roles["main_ensembles"], roles["classifiers"]
    if not set(MAIN_CLASSIFIERS) <= set(cls_all):
        raise ValueError(f"MAIN_CLASSIFIERS {MAIN_CLASSIFIERS} not all in the analysis classifiers {cls_all}")
    cls = list(MAIN_CLASSIFIERS)
    clip = {**clip_labels(roles["clip_label"]), "label": roles["clip_label"]}
    time_normalised(res, ens, out / FILES["time_normalised"])
    time_normalised_variants(res, ens, out / FILES["time_normalised_variants"])
    member_count(res, ens, out / FILES["member_count"])
    action_perturbations(res, ens, roles["actions"], out / FILES["actions"])
    relabeling_frames(res, ens, out / FILES["frames"])
    random_vs_nearest(res, ens, cls, clip, out / FILES["nearest"])
    detector_comparison(res, ens, cls, clip, out / FILES["all"])
    object_removal_operating_point(res, ens, cls, clip, roles["table_alpha"], out / FILES["operating_point"])
    controls(res, ens, cls, clip, masks, roles["table_alpha"], out / FILES["controls"])
    encoder_novelty(res, ens, spearman, out / FILES["encoder"])
    classifier_variants(res, cls_all, roles["classifier_notes"], out / FILES["classifiers"])
    reward_ablation(res, roles["ablations"], roles["reference_ensemble"], out / FILES["reward"])
    return latency(latency_json, out / FILES["latency"])


DOMAIN_ROWS = (("train", "Training"),
               ("eval_seen", "Test, seen task"),
               ("eval_unseen", "Test, unseen task"))


def seen_unseen_domains(domains: dict, ens: list[str], out: Path, scope: str = "bridge") -> None:
    """Rows: SayNo variant x (training trajectories, held-out with a training instruction, held-out with
    an instruction not in the training split); columns: counterfactual relabeling and object removal, sigma_Q
    and -Qbar at the average of both frames. Written by src/scripts/instruction_overlap.py."""
    conds = ("lang_swap_train", "inpaint")
    ncol = 2 + 2 * len(conds)
    body = []
    for g, lab in enumerate(ens):
        body.append(group_row(model_name(lab), ncol, g == 0))
        for key, name in DOMAIN_ROWS:
            r = domains[lab][scope][key]
            body.append([indent(name), str(r["n"])] + [pm(r["cells"][c][rd]) for c in conds for rd in ENS_SCORES])
    tab = booktabs(["Evaluation Split", "Demonstrations"] + [SCORE_SYMBOLS[rd] for _ in conds for rd in ENS_SCORES], body,
                   align="@{}lr" + "c" * (2 * len(conds)) + "@{}",
                   group_header=[("", 2)] + [(title_case(condition_name(c, sole_relabeling=True)), len(ENS_SCORES))
                                             for c in conds])
    caption = (r"AUROC of SayNo on Bridge demonstrations of the training split and of the test split, the latter "
               r"divided by whether the demonstration's own instruction occurs in training (seen task) or not "
               r"(unseen task). Fractal is left out because all its test instructions "
               r"occur in training.")
    write(out, tab, caption, "tab:bf-seen-unseen-task",
          [P_AUROC, P_BOTH, P_RELABEL_SOLE, P_RHO,
           "task = exact instruction string; seen = occurs in >= 1 Bridge training-split trajectory "
           "(instruction-overlap-bridge-fractal/instructions_bridge_fractal_full.hdf5)",
           "not marked: rows compare trajectory groups, not detectors"],
          generator=("generated by src/scripts/instruction_overlap.py (say_no.perturbation.thesis_tables) from "
                     "instruction-overlap-bridge-fractal/instruction_overlap.json; do not edit; invocation: "
                     "docs/REPRODUCE.md"))
