"""Thesis tables of the episode-level IVA detector, rendered from the saved
`episode_statistics.json` (producer: src/scripts/cp/analyse_episode_statistics.py).

Rendering only: every number is read from the JSON, whose values are pinned in
tests/test_episode_statistics_numbers.py.

Marking rule: say_no.perturbation.tables.ranks (shared with the Bridge/Fractal tables).
Recalls are ranked only among rows whose episode FAR <= alpha, since a detector with
more false alarms buys its recall. Tables whose rows are not alternatives (test-split composition, per
task) carry no marks.
"""

from pathlib import Path

from say_no.perturbation.tables import booktabs, ranks, stack, write_table

DIGITS = 3  # decimals of rates and AUROCs
# Reader-facing names, as used in the thesis.
STATISTIC_NAMES = {"max": "Maximum", "topk_mean5": "Top-5 mean", "count_above": "Count",
                   "frac_above": "Fraction", "cusum": "CUSUM"}
# IVA paper Table 1 spelling (hsieh2025).
TASK_NAMES = {"close_jar": "Close jar", "meat_off_grill": "Meat off grill",
              "open_drawer": "Open drawer", "push_buttons": "Push buttons",
              "put_money_in_safe": "Put money in safe", "reach_and_drag": "Reach and drag",
              "slide_block_to_color_target": "Slide block", "sweep_to_dustpan_of_size":
              "Sweep to dustpan", "turn_tap": "Turn tap"}
# the RLBench model is a separate model from the Bridge/Fractal SayNo-CR (rho = 10 %); the caption
# names its training data so the two are not read as one; its recipe is in the thesis text
MODEL = r"SayNo trained on the IVA training split"
BOTH = r"$\sigma_{Q,t}$ and $-\bar Q_t$"
VALUE = r"$-\bar Q_t$ only"
# IVA's instruction of another task on every frame = the thesis' counterfactual relabeling
RELABEL = stack("Counterfactual", "Relabeling")


def group_label(text, ncol):
    return r"\multicolumn{" + str(ncol) + r"}{l}{\textit{" + text + r"}} \\"


def _wrap(s, mark):
    return {None: s, "bold": r"\mathbf{" + s + "}", "underline": r"\underline{" + s + "}"}[mark]


def cell(v, digits=DIGITS, mark=None, ci=None):
    """Math-mode number; `ci` = (lo, hi) is shown as distances to the interval bounds, which
    keeps the Wilson interval's asymmetry (a symmetric +- would misstate the bound near 0).
    The distances drop the leading zero: same digits, a narrower column."""
    s = _wrap(f"{v:.{digits}f}", mark)
    if ci is not None:
        # distances between DISPLAYED values, so value +- distance gives the rounded bound
        lo, hi, v = (shown(x, digits) for x in (*ci, v))
        assert lo <= v <= hi and hi - v < 1 and v - lo < 1, (lo, v, hi)
        dist = lambda x: f"{x:.{digits}f}".lstrip("0")
        s += "^{+" + dist(hi - v) + "}_{-" + dist(v - lo) + "}"
        # strut: scripts of adjacent rows would touch; only these rows grow, not the header
        return f"${s}$" + r"\rule[-1.1ex]{0pt}{3.3ex}"
    return f"${s}$"


def shown(v, digits=DIGITS):
    """The value the reader sees; ranking uses it, not the unrounded float."""
    return round(v, digits)


def protocol_comment(res, name):
    """Provenance and protocol minutiae, written as `%` comments into the table."""
    ep = _statistic(res, "max", "both")
    return "\n".join([
        f"{name}.tex -- generated by src/scripts/cp/write_iva_thesis_tables.py from",
        "src/results/episode-operating-point-iva/thesis/episode_statistics.json; do not edit.",
        f"JSON producer: {res['command']}",
        f"Model: {res['model_dir'].rsplit('/', 1)[-1]}, step {res['step']}, "
        f"{res['n_members']} members.",
        f"Protocol: split conformal episode threshold, {res['n_folds']} folds x analysis seeds "
        f"{res['seeds']} ({res['n_folds'] * len(res['seeds'])} calibrations); each episode scored "
        "by a fold that did not calibrate on it; per-task time-normalisation of each score "
        "(mean/std of TP calibration episodes at each frame position), max over the two scores; "
        f"conformal quantile pooled across tasks; {ep['n_episodes_excluded_from_calibration']} "
        f"episodes < {ep['min_calib_len']} frames excluded from calibration (still scored).",
        "Intervals: 95% Wilson on distinct episodes (analysis seeds re-score the same episodes; "
        "the relabeled instructions of one episode alarm together, so n = "
        f"{ep['n_eff_foreign']} episodes, not {ep['n_foreign_episode_scorings']} scorings). "
        "Count/fraction/CUSUM threshold tau = (1 - tau_alpha) quantile of TP "
        f"calibration frames, tau_alpha = {res['tau_alpha']:g}, fixed a priori.",
        "Marks: see say_no.cp.thesis_tables docstring (bold best, underline second, "
        "recalls ranked only among rows with FAR <= alpha).",
    ])


def _write(out_dir, name, res, tabular, caption, note=None, size=r"\setlength{\tabcolsep}{5pt}"):
    write_table(Path(out_dir) / f"{name}.tex", [tabular], caption, "tab:" + name.replace("_", "-"),
                size=size, comment=protocol_comment(res, name), note=note)
    print(f"wrote {Path(out_dir) / f'{name}.tex'}")


def thin(n):
    return f"{n:,}".replace(",", r"\,")


def test_split_composition(res, out_dir):
    split = res["eval_split"]
    rows = []
    for t, s in split.items():
        rows.append([TASK_NAMES[t], str(s["n_episodes"]), str(s["n_iva_episodes"]),
                     thin(s["n_frames"]), thin(s["n_injected_frames"]),
                     cell(s["n_injected_frames"] / s["n_frames"])])
    tot = {k: sum(s[k] for s in split.values()) for k in next(iter(split.values()))}
    rows.append(["All tasks", str(tot["n_episodes"]), str(tot["n_iva_episodes"]),
                 thin(tot["n_frames"]), thin(tot["n_injected_frames"]),
                 cell(tot["n_injected_frames"] / tot["n_frames"])])
    tab = booktabs(["Task", "Episodes", stack("FP", "Episodes"), "Frames", stack("FP", "Frames"),
                    stack("FP Frame", "Share")], rows, align="lrrrrr", midrule_after=[len(rows) - 2])
    _write(out_dir, "iva_test_split_composition", res, tab,
           r"Composition of the IVA test split used for all RLBench results. An FP episode "
           r"contains at least one false-premise (FP) frame, whose instruction names an object "
           r"that is absent from the scene; all other frames are true-premise (TP) frames.")


def frame_auroc_reward_design(res, out_dir):
    # The rho = 0 run trained on non-consecutive SARSA transitions (data-loading error); it stays in the JSON, not in the thesis.
    rd = [r for r in res["reward_design"] if r["negdemo_ratio"] > 0]
    assert len(rd) == len(res["reward_design"]) - 1 and len({r["negdemo_ratio"] for r in rd}) == 1
    m_iva = ranks([r["auroc_iva_injection"] for r in rd], True, digits=DIGITS)
    m_ct = ranks([r["auroc_foreign_instruction"] for r in rd], True, digits=DIGITS)
    rows = [[f"${r['step_reward']:g}$", f"{r['step'] // 1000}k",
             cell(r["auroc_iva_injection"], mark=a), cell(r["auroc_foreign_instruction"], mark=b)]
            for r, a, b in zip(rd, m_iva, m_ct)]
    tab = booktabs([stack("Step", "Reward"), stack("Training", "Steps"), stack("FP", "Injection"),
                    RELABEL], rows, align="cccc", group_header=[("", 2), ("AUROC", 2)])
    _write(out_dir, "iva_frame_auroc_reward_design", res, tab,
           r"Frame-level AUROC of the ensemble disagreement $\sigma_{Q,t}$ for " + MODEL +
           r" with and without a step reward. "
           r"Negatives are the TP frames of the IVA test split (9 tasks) under their own "
           r"instruction; positives are its FP frames, scored under the false-premise injection or "
           r"under counterfactual relabeling with another task's instruction, and each AUROC is "
           r"the mean over tasks. Marks compare values per column.")


def _statistic(res, statistic, frame_statistic):
    hits = [r for r in res["statistics"]
            if r["statistic"] == statistic and r["frame_statistic"] == frame_statistic]
    assert len(hits) == 1, (statistic, frame_statistic)
    return hits[0]


def _op_cells(o, marks=(None, None)):
    return [cell(o["episode_far"], ci=o["far_ci"]),
            cell(o["episode_recall_iva_injection"], mark=marks[0], ci=o["recall_iva_ci"]),
            cell(o["episode_recall_foreign_instruction"], mark=marks[1], ci=o["recall_foreign_ci"])]


def _far_range(o):
    """Episode FAR of the best and worst single calibration: one deployment calibrates once."""
    b = o["episode_far_by_calibration"]
    assert len(b) == o["n_calibrations"], (len(b), o["n_calibrations"])
    return f"${min(b):.{DIGITS}f}$--${max(b):.{DIGITS}f}$"


def episode_detection(res, out_dir):
    """Main-text table, the deployed detector: a frame-level threshold with the episode as the
    decision unit, the episode-level threshold at every swept alpha, the value score alone."""
    f = res["frame_level"]
    sweep = res["alpha_sweep"]
    alphas = sorted({o["alpha"] for o in sweep}, reverse=True)
    by = {(o["frame_statistic"], o["alpha"]): o for o in sweep}
    assert len(by) == len(sweep) == 2 * len(alphas) and f["frame_statistic"] == "both"
    assert f["alpha"] == res["alpha"]
    # Comparison group = the two detection scores at the headline alpha.
    pair = [by[("both", res["alpha"])], by[("neg_mean_q", res["alpha"])]]
    ok = [o["episode_far"] <= res["alpha"] for o in pair]
    marks = [ranks([o[k] for o in pair], True, ok, digits=DIGITS)
             for k in ("episode_recall_iva_injection", "episode_recall_foreign_instruction")]

    def row(label, o, ms):
        far, ri, rf = _op_cells(o, ms)
        return [label, f"${o['alpha']:.2f}$", far, _far_range(o), ri, rf]

    head = ["Threshold", r"Nominal $\alpha$", "Episode FAR", stack("Episode FAR,", "Single Calibration"),
            stack("FP", "Injection"), RELABEL]
    rows = [group_label(BOTH, len(head)),
            ["Frame-level", f"${f['alpha']:.2f}$", cell(f["episode_far_any_frame"]), "--",
             cell(f["episode_recall_iva_any_frame"]), cell(f["episode_recall_foreign_any_frame"])]]
    rows += [row("Episode-level", by[("both", al)],
                 (marks[0][0], marks[1][0]) if al == res["alpha"] else (None, None)) for al in alphas]
    rows += [group_label(VALUE, len(head)), row("Episode-level", pair[1], (marks[0][1], marks[1][1]))]
    tab = booktabs(head, rows, align="lccccc", group_header=[("", 4), ("Recall", 2)],
                   midrule_after=[len(alphas) + 1])
    # widest IVA table (six columns, interval scripts): smaller font and gaps, as set in the thesis
    _write(out_dir, "iva_episode_detection", res, tab, size="\\small\n\\setlength{\\tabcolsep}{4pt}", caption=
           r"Episode false-alarm rate (FAR) and recall of SayNo as a stopping detector on the IVA "
           r"test split (9 tasks). The frame-level threshold is the conformal quantile of TP frames "
           r"and stops an episode at the first frame above it; the episode-level threshold is the "
           r"conformal quantile of the maximum score over TP calibration episodes. The FAR column "
           r"pools " + str(pair[0]["n_calibrations"]) + r" cross-fitted calibrations, the next "
           r"column gives the lowest and highest FAR of a single calibration. Recall is the share "
           r"of FP episodes with an alarm under the false-premise injection, or of all episodes "
           r"under counterfactual relabeling with another task's instruction. Bold:"
           r" the higher recall of the two scores at $\alpha = " + f"{res['alpha']:g}" + r"$.")


def episode_statistic_comparison(res, out_dir):
    alpha = res["alpha"]
    both = [r for r in res["statistics"] if r["frame_statistic"] == "both"]
    value = [r for r in res["statistics"] if r["frame_statistic"] == "neg_mean_q"]
    assert len(both) == 5 and len(value) == 1
    ok = [r["episode_far"] <= alpha for r in both]
    cols = [("episode_recall_iva_injection", ok, "recall_iva_ci"),
            ("episode_recall_foreign_instruction", ok, "recall_foreign_ci"),
            ("episode_auroc_iva_injection", None, None),
            ("episode_auroc_foreign_instruction", None, None)]
    marks = [ranks([r[k] for r in both], True, e, digits=DIGITS) for k, e, _ in cols]

    def row(r, ms):
        return [STATISTIC_NAMES[r["statistic"]], cell(r["episode_far"], ci=r["far_ci"]),
                *[cell(r[k], mark=m, ci=r[c] if c else None) for (k, _, c), m in zip(cols, ms)]]

    head = ["Episode Statistic", "Episode FAR", stack("FP", "Injection"),
            RELABEL, stack("FP", "Injection"),
            RELABEL]
    rows = [group_label(BOTH, len(head))]
    rows += [row(r, [m[i] for m in marks]) for i, r in enumerate(both)]
    rows += [group_label(VALUE, len(head)), row(value[0], [None] * 4)]
    tab = booktabs(head, rows, align="lccccc", midrule_after=[len(both)],
                   group_header=[("", 2), ("Recall", 2), ("AUROC", 2)])
    _write(out_dir, "iva_episode_statistic_comparison", res, tab, caption=
           r"Episode false-alarm rate (FAR), recall and threshold-free AUROC of five "
           r"episode statistics at $\alpha = " + f"{alpha:g}" + r"$. All rows use " + MODEL +
           r", on the IVA test split (9 tasks); the last row uses the value score $-\bar Q_t$ "
           r"alone and is not ranked. Marks compare the statistics on both scores; a recall is "
           r"ranked only if its FAR does not exceed $\alpha$.")


def per_task_operating_point(res, out_dir):
    ep = _statistic(res, "max", "both")
    rows = [[TASK_NAMES[t], str(v["n_feasible_episodes"]), str(v["n_iva_episodes"]),
             cell(v["far"]), cell(v["recall_iva"]), cell(v["recall_foreign"])]
            for t, v in ep["per_task"].items()]
    tab = booktabs(["Task", "Episodes", stack("FP", "Episodes"), stack("Episode", "FAR"),
                    stack("FP", "Injection"), RELABEL], rows,
                   align="lrrccc", group_header=[("", 4), ("Recall", 2)])
    n = sorted({v["n_feasible_episodes"] for v in ep["per_task"].values()})
    n_text = f"{n[0]} to {n[-1]}" if len(n) > 1 else str(n[0])
    _write(out_dir, "iva_per_task_operating_point", res, tab,
           r"Episode false-alarm rate (FAR) and recall per IVA task at the operating "
           r"point of Table~\ref{tab:iva-episode-detection} (episode-level threshold, both "
           r"scores, $\alpha = " + f"{res['alpha']:g}" + r"$). One threshold is shared by all "
           r"tasks; each task contributes " + n_text + r" test episodes.")


TABLES = (episode_detection, test_split_composition, frame_auroc_reward_design,
          episode_statistic_comparison, per_task_operating_point)


def write_all(res, out_dir):
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    for fn in TABLES:
        fn(res, out_dir)
